#!/bin/bash
# ============================================================================
# DexDiff funnel — sandboxed end-to-end loop closure
#
# Proves the full QR chain in a temp vault against a LOCAL stub of
# api.heydex.ai serving the real v2 re-seed payload:
#
#   1. build the stub bundle from seed-data/dave-profile-v2 (reseed-v2 --emit-bundle)
#   2. start a local HTTP stub serving GET /api/profile-bundle?handle=davekilleen
#   3. create a fresh temp vault (stranger's machine stand-in)
#   4. run install-diff.sh into it           (break 0 fixed)
#   5. adopt: fetch via the installed skill script against the stub
#                                            (breaks 1+2+3 fixed)
#   6. simulate the conversational generation step with a deterministic
#      stand-in for the adopter's AI (the real step is Claude Code itself,
#      which is NOT invoked here by design)
#   7. verify the adoption record + artifacts and print the evidence
#
# Run: bash scripts/sandbox-loop.sh
# No production access, no real claude invocation, everything under /tmp.
# ============================================================================
set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK="$(mktemp -d /tmp/dexdiff-sandbox-loop.XXXXXX)"
VAULT="$WORK/stranger-vault"
BUNDLE="$WORK/stub-bundle.json"
STUB_PORT=0
STUB_PID=""

cleanup() { [ -n "$STUB_PID" ] && kill "$STUB_PID" 2>/dev/null || true; }
trap cleanup EXIT

step() { echo ""; echo "━━━ $1"; }

step "1/7 Build the stub bundle from the v2 re-seed payload"
node "$REPO_ROOT/scripts/reseed-v2.cjs" --emit-bundle "$BUNDLE" | tail -2

step "2/7 Start the local production-API stub"
python3 - "$BUNDLE" > "$WORK/stub-port" <<'PY' &
import http.server, json, socketserver, sys, threading

bundle_path = sys.argv[1]
with open(bundle_path, "r", encoding="utf-8") as f:
    BUNDLE = f.read()

class Handler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        from urllib.parse import urlparse, parse_qs
        parsed = urlparse(self.path)
        params = parse_qs(parsed.query)
        if parsed.path == "/api/profile-bundle" and params.get("handle", [""])[0] == "davekilleen":
            body = BUNDLE.encode("utf-8")
            self.send_response(200)
        elif parsed.path == "/api/diffs":
            body = b"[]"
            self.send_response(200)
        else:
            body = json.dumps({"error": "Profile bundle not found"}).encode("utf-8")
            self.send_response(404)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)
    def log_message(self, *a):
        pass

with socketserver.TCPServer(("127.0.0.1", 0), Handler) as httpd:
    print(httpd.server_address[1], flush=True)
    httpd.serve_forever()
PY
STUB_PID=$!
for i in $(seq 1 50); do [ -s "$WORK/stub-port" ] && break; sleep 0.1; done
STUB_PORT="$(cat "$WORK/stub-port")"
echo "stub serving the davekilleen bundle on 127.0.0.1:$STUB_PORT (pid $STUB_PID)"

step "3/7 Create a fresh temp vault (the stranger's machine)"
mkdir -p "$VAULT/.claude"
echo "# A fresh Dex vault" > "$VAULT/CLAUDE.md"
echo "$VAULT"

step "4/7 Bootstrap: install the diff commands (curl|bash equivalent)"
( cd "$VAULT" && cat "$REPO_ROOT/install-diff.sh" | bash )

step "5/7 Adopt: fetch @davekilleen through the installed skill script (stubbed API)"
echo "--- fetch-only (what the agent shows before asking consent) ---"
( cd "$VAULT" && DEXDIFF_API_BASE="http://127.0.0.1:$STUB_PORT" \
    python3 .claude/skills/diff-adopt-profile/scripts/adopt_profile.py @davekilleen --fetch-only )
echo "--- full save (after consent) ---"
( cd "$VAULT" && DEXDIFF_API_BASE="http://127.0.0.1:$STUB_PORT" \
    python3 .claude/skills/diff-adopt-profile/scripts/adopt_profile.py @davekilleen )

step "6/7 Generate a workflow into the vault (SANDBOX STAND-IN for the adopter's AI)"
# In the real funnel, Claude Code reads the saved methodology and generates a
# tailored skill conversationally. The sandbox must not invoke claude, so this
# deterministic stand-in proves the wiring: methodology in -> skill out.
python3 - "$VAULT" <<'PY'
import re, sys
from pathlib import Path

vault = Path(sys.argv[1])
workflow = vault / "04-Projects/DexDiff/beta/profile/adopted/davekilleen/workflows/01-meeting-intelligence.yaml"
text = workflow.read_text(encoding="utf-8")

name = re.search(r'^name: "(.*)"$', text, re.M).group(1)
description = re.search(r'^description: "(.*)"$', text, re.M).group(1)

skill_dir = vault / ".claude/skills/meeting-intelligence"
skill_dir.mkdir(parents=True, exist_ok=True)
(skill_dir / "SKILL.md").write_text(
    "---\n"
    "name: meeting-intelligence\n"
    f"description: {description[:140]}\n"
    "---\n\n"
    f"# {name}\n\n"
    "<!-- SANDBOX ARTIFACT: generated by the rehearsal driver as a\n"
    "     deterministic stand-in for the adopter's AI. In the real flow\n"
    "     Claude Code generates this from the methodology below, tailored\n"
    "     to the user's role and folders. -->\n\n"
    "Generated from the adopted methodology at:\n"
    "04-Projects/DexDiff/beta/profile/adopted/davekilleen/workflows/01-meeting-intelligence.yaml\n"
    f"({len(text):,} chars of v2 methodology)\n",
    encoding="utf-8",
)
print(f"generated .claude/skills/meeting-intelligence/SKILL.md from {len(text):,} chars of methodology")
PY

step "7/7 Verify the loop actually closed"
python3 - "$VAULT" <<'PY'
import json, sys
from pathlib import Path

vault = Path(sys.argv[1])
failures = []

def check(label, ok):
    print(("  ok    " if ok else "  FAIL  ") + label)
    if not ok:
        failures.append(label)

skills = vault / ".claude/skills"
check("7 bootstrap files installed", sum(1 for p in skills.rglob("*") if p.is_file() and "meeting-intelligence" not in str(p)) == 7)

adopted = vault / "04-Projects/DexDiff/beta/profile/adopted/davekilleen"
check("bundle manifest saved", (adopted / "profile-bundle.json").is_file())
workflows = sorted((adopted / "workflows").glob("*.yaml"))
check("8 workflow methodologies saved", len(workflows) == 8)
big = all(p.stat().st_size > 20000 for p in workflows)
check("every methodology is full v2 size (>20KB, not a 227-char summary)", big)

log_path = vault / "System/.dex/adoptions/profiles/davekilleen.json"
check("adoption record written", log_path.is_file())
if log_path.is_file():
    log = json.loads(log_path.read_text())
    check("adoption record lists all 8 workflow ids", len(log.get("workflow_ids", [])) == 8)
    print("\n  ADOPTION RECORD (the first ever):")
    for key in ("profile_handle", "profile_display_name", "adopted_at", "source", "bundle_contract_version"):
        print(f"    {key}: {log.get(key)}")
    print(f"    workflow_ids: {log.get('workflow_ids')}")

check("generated skill exists", (vault / ".claude/skills/meeting-intelligence/SKILL.md").is_file())

print()
if failures:
    print(f"LOOP DID NOT CLOSE — {len(failures)} failure(s)")
    sys.exit(1)
print("LOOP CLOSED: bootstrap -> fetch -> save -> generate -> adoption record. All green.")
PY

echo ""
echo "Sandbox artifacts kept for inspection: $WORK"
